trigger:
  branches:
    include:
    - main
  tags:
    include: ['*']

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  buildProjects: '**/*.csproj;!**/*.Tests.csproj'
  testProjects: '**/*Tests/*.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6.x SDK'
  inputs:
    version: 6.x

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(buildProjects)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(testProjects)'
    arguments: '--configuration $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)'
    artifactName: Build_Package
